version: '3.7'
services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./Tests:/var/www/html/Tests

  mysql:
    image: mysql:8.0.3
    environment:
      MYSQL_DATABASE: hive
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:community
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false&serverTimezone=UTC
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_HTTPS_PORT=9000
      - SONARQUBE_CONTEXT=/
      - SONAR_HOST_URL=http://localhost:9000
    volumes:
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/data:/opt/sonarqube/data