version: '3.7'
services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./Tests:/var/www/html/Tests

  mysql:
    image: mysql:8.0.3
    environment:
      MYSQL_DATABASE: hive
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"