version: '3.7'
services:
  php:
    build: .
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: hive
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql

  jenkins: 
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=Wijte1997.     